services:
  - type: web
    name: expense-prediction-api
    env: python
    plan: free
    buildCommand: |
      # Upgrade pip, setuptools, and wheel first
      python -m pip install --upgrade pip setuptools wheel
      # Then install project dependencies
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 300